REPORT zemp_salary_calc.

TABLES: zmk_emp, zemp_track02, zemp_salaryslip.

PARAMETERS: 
  p_empid TYPE zmk_emp-zempid OBLIGATORY,
  p_month TYPE char6 AS LISTBOX VISIBLE LENGTH 10. "Dropdown for month

DATA: wa_emp     TYPE zmk_emp,
      wa_slip    TYPE zemp_salaryslip,
      lv_total_present TYPE i,
      lv_total_leave   TYPE i,
      lv_net_salary    TYPE p DECIMALS 2,
      lv_basic         TYPE zmk_emp-salary,
      lt_months        TYPE TABLE OF char6,
      lv_date          TYPE d,
      lv_user          TYPE sy-uname,
      lv_slipid        TYPE zemp_salaryslip-salslipid.

INITIALIZATION.
  DATA: lv_index TYPE i,
        lv_yyyymm TYPE char6.

  DO 12 TIMES.
    lv_index = sy-index.
    lv_date = sy-datum.
    "Calculate first day of each month (current year)
    lv_date+0(4) = sy-datum+0(4).   "Current Year
    lv_date+4(2) = lv_index MOD 12 + 1.
    lv_date+6(2) = '01'.
    lv_yyyymm = lv_date+0(6).
    APPEND lv_yyyymm TO lt_months.
  ENDDO.

  p_month = lt_months[ 1 ]. "Default month

START-OF-SELECTION.

* Check Employee existence
SELECT SINGLE * FROM zmk_emp
  WHERE zempid = @p_empid
  INTO @wa_emp.

IF sy-subrc <> 0.
  MESSAGE 'Employee does not exist in master table' TYPE 'E'.
ENDIF.

lv_basic = wa_emp-salary.
lv_user  = sy-uname.
lv_date  = sy-datum.

* Count total present days in the selected month
SELECT COUNT(*) FROM zemp_track02
  WHERE zempid    = @p_empid
    AND emp_month = @p_month
    AND emp_status = 'P'
  INTO @lv_total_present.

* Count total leave days in the selected month
SELECT COUNT(*) FROM zemp_track02
  WHERE zempid    = @p_empid
    AND emp_month = @p_month
    AND emp_status = 'L'
  INTO @lv_total_leave.

* Calculate Net Salary based on present days
"Assuming month has 30 days
lv_net_salary = lv_basic * lv_total_present / 30.

* Generate unique Salary Slip ID
CONCATENATE 'SLIP' p_month p_empid INTO lv_slipid.

* Fill Salary Slip structure
wa_slip-salslipid   = lv_slipid.
wa_slip-zempid      = p_empid.
wa_slip-sal_month   = p_month.
wa_slip-basic       = lv_basic.
wa_slip-total_present = lv_total_present.
wa_slip-total_leave   = lv_total_leave.
wa_slip-net_salary    = lv_net_salary.
wa_slip-created_on    = lv_date.
wa_slip-created_by    = lv_user.

* Insert or Update Salary Slip
SELECT SINGLE * FROM zemp_salaryslip
  WHERE zempid = @p_empid
    AND sal_month = @p_month
  INTO @DATA(ls_check).

IF sy-subrc = 0.
  "Update existing slip
  UPDATE zemp_salaryslip
     SET total_present = @lv_total_present,
         total_leave   = @lv_total_leave,
         net_salary    = @lv_net_salary,
         created_on    = @lv_date,
         created_by    = @lv_user
   WHERE zempid     = @p_empid
     AND sal_month  = @p_month.
ELSE.
  "Insert new slip
  INSERT zemp_salaryslip FROM wa_slip.
ENDIF.


FORMAT COLOR COL_HEADING INTENSIFIED ON.
WRITE: / '===================== SALARY SLIP ====================='.
FORMAT COLOR OFF.

ULINE.

WRITE: / 'SALARY SLIP ID      : ', lv_slipid,
       / 'EMPLOYEE ID        : ', wa_emp-zempid,
       / 'EMPLOYEE NAME      : ', wa_emp-zname,
       / 'MONTH              : ', p_month,
       / 'BASIC SALARY       : ', lv_basic,
       / 'TOTAL PRESENT DAYS : ', lv_total_present,
       / 'TOTAL LEAVE DAYS   : ', lv_total_leave,
       / 'NET SALARY         : ', lv_net_salary,
       / 'GENERATED ON       : ', lv_date,
       / 'GENERATED BY       : ', lv_user.

ULINE.

FORMAT COLOR COL_POSITIVE INTENSIFIED ON.
WRITE: / '✔ Salary slip generated successfully'.
FORMAT COLOR OFF.

WRITE: / '======================================================='.
